// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Planim;
//
//    var claseJuego = ClaseJuego.FromJson(jsonString);

namespace Planim
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ClaseJuego
    {
        [JsonProperty("$id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("Actividad")]
        public object Actividad { get; set; }

        [JsonProperty("Ambitos")]
        public object Ambitos { get; set; }

        [JsonProperty("MaterialesxJuegos")]
        public List<MaterialesxJuego> MaterialesxJuegos { get; set; }

        [JsonProperty("idJuego")]
        public long IdJuego { get; set; }

        [JsonProperty("Nombre")]
        public string Nombre { get; set; }

        [JsonProperty("Explicacion")]
        public string Explicacion { get; set; }

        [JsonProperty("idAmbito")]
        public long IdAmbito { get; set; }

        [JsonProperty("idActividad")]
        public object IdActividad { get; set; }

        [JsonProperty("Orden")]
        public object Orden { get; set; }

        [JsonProperty("Tiempo")]
        public object Tiempo { get; set; }

        [JsonProperty("idJuegoVariante")]
        public object IdJuegoVariante { get; set; }

        [JsonProperty("EdadRecomendada")]
        public long EdadRecomendada { get; set; }

        [JsonProperty("CantNiñosRecom")]
        public long CantNiñosRecom { get; set; }
    }

    public partial class MaterialesxJuego
    {
        [JsonProperty("$id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("Juegos")]
        public Juegos Juegos { get; set; }

        [JsonProperty("Materiales")]
        public object Materiales { get; set; }

        [JsonProperty("idMatxJue")]
        public long IdMatxJue { get; set; }

        [JsonProperty("idMaterial")]
        public long IdMaterial { get; set; }

        [JsonProperty("idJuego")]
        public long IdJuego { get; set; }
    }

    public partial class Juegos
    {
        [JsonProperty("$ref")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Ref { get; set; }
    }

    public partial class ClaseJuego
    {
        public static List<ClaseJuego> FromJson(string json) => JsonConvert.DeserializeObject<List<ClaseJuego>>(json, Planim.Converter.Settings);
    }

}
